@echo off
echo Установка зависимостей...
pip install -r requirements.txt
echo Установка браузеров Playwright...
playwright install
echo Запуск парсера...
python 2gis_parser.py --city "Астана" --categories "кофейни" "салоны красоты" "магазины одежды" --max-items 50
pause